### ISSUE TITLE
Drawing roadnet failed

### ISSUE THREAD

**Issue by Danny-wenya** [zyr17/UniLight#1]
Hi,
Could you please help me the problem? I downloaded the code from "https://github.com/zyr17/UniLight" and ran it, then I got my replay.txt and roadnet.json files, I opened them in my google browser and got "Drawing roadnet failed" feedback. How can I solve this problem?

**Comment by zyr17** [comment]
Which version of CityFlow did you use, the original one or my forked one? Could you please provide replay.txt and roadnet.json that failed to load?

**Comment by Danny-wenya** [comment]
I ran the commands in the README file with defualt setting, so I think I've used your forked Cityflow version. 
I tried offical example by running download_replay.py, loading files to the frontend and I got "Error occurred when drawing". btw I use google browser.
The files I used is in this netdisk link:https://pan.baidu.com/s/1sWg_CEVEj4se8_Uu22fmUw?pwd=ozkl    pwd:ozkl 
Look forward to your replay!

**Comment by zyr17** [comment]
Sorry, `download.py` is from the original CityFlow, it downloads the original replay and may not be supported by my forked version.

The reason of error is that you're using wrong roadnet file. CityFlow generated a separate roadnet.json along with the replay.txt, which is different to the roadnet.json in the dataset. Refer to https://cityflow.readthedocs.io/en/latest/replay.html. 
Another problem is that when the replay file is too large, frontend may stuck in parsing replay file (in my computer, large than ~1GB, threshold may be various for different devices), you can use `head` or `tail` to get part of the file and replay.

**Comment by Danny-wenya** [comment]
Yes! I found the right roadnet.json file and succeed! Thank you for help!😃😃



---Original---
From: ***@***.***&gt;
Date: Sun, Oct 8, 2023 00:33 AM
To: ***@***.***&gt;;
Cc: "Danny ***@***.******@***.***&gt;;
Subject: Re: [zyr17/UniLight] Drawing roadnet failed (Issue #1)




 
Sorry, download.py is from the original CityFlow, it downloads the original replay and may not be supported by my forked version.
 
The reason is that you're using wrong roadnet file. CityFlow generated a separate roadnet.json along with the replay.txt, which is different to the roadnet.json in the dataset. Refer to https://cityflow.readthedocs.io/en/latest/replay.html.
 Another problem is that when the replay file is too large, frontend may stuck in parsing replay file (in my computer, large than ~1GB, threshold may be various for different devices), you can use head or tail to get part of the file and replay.
